sudo: false
os: linux
language: haskell
addons:
  apt:
    packages:
    - texlive-latex-recommended lmodern texlive-fonts-recommended texlive-latex-extra
      texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-french
before_install:
- sudo add-apt-repository -y ppa:jonathonf/python-2.7
- sudo apt-get update
- sudo apt-get install python2.7  librsvg2-bin
install:
- wget https://github.com/jgm/pandoc/releases/download/2.0.6/pandoc-2.0.6-1-amd64.deb
- sudo dpkg -i pandoc-2.0.6-1-amd64.deb
- wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.0.1/linux-ghc80-pandoc20.tar.gz
- mkdir pandoc-crossref
- cd pandoc-crossref
- mv ../linux-ghc80-pandoc20.tar.gz .
- tar xzvf linux-ghc80-pandoc20.tar.gz
- cd ..
- export PATH=`pwd`/pandoc-crossref:$PATH
- sudo -H pip install --upgrade pip
- sudo -H pip install -U pandoc-numbering
cache:
- pip
script:
- make
after_deploy: |
  git config --global user.email "travis@travis-ci.org"
  git config --global user.name "Travis CI"
  cd "$TRAVIS_BUILD_DIR"
  git clone https://${GH_TOKEN}@github.com/mathintro/mathintro.github.io.git
  cd mathintro.github.io
  # This generates a `web` directory containing the website.
  cp ../cours.html deuxieme_logiciel/index.html
  git add deuxieme_logiciel/index.html
  git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  # Make sure to make the output quiet, or else the API token will leak!
  # This works because the API key can replace your password.
  git push --quiet https://${GH_TOKEN}@github.com/mathintro/mathintro.github.io.git


 deploy:

  provider: releases
  api_key:
    secure: VktZE8/zUOMOzOjAie1ePOqbRbH53jgGt0abzK9Cc8Hpq9qH1nleBFSU/Dpypxrs3d/AtpvZTTQRFG3OsDqEyOewWOLmaG3DSVIyGz+Tva4KFNNcROVvzbsldnG1hx2MqX0icMOZIdTa+l2vCN08ix6mMsQUJmWswA6YB3SSvJiJBwmC36692B1ac6zmDG7n6GEFRR7PpTNA8x3BAMM2CUO8rrkiWTPmD2oL0fFrMmWdtDEoP/QGFBaRc7sSjzR3vfhVFZOoT/lpk6V6WZuBgwRuNs2yDola2GAmIgJzaT8Ngg/+Sdb2jgYVVoI3z68ijKyGkRY+G4CI4NVHMkm5xriAoet7MqE20F9/gfQ7RO9sm7Ybpw1BwaME2kKHss9Q+IH0jgHBE+fWNFLMG4yR63w7icd6E/fTQ0Pes8FzQiq/QBKrHYAgigDzpjG1t7dqX+lB9fVmQkyy/OnaQs8va0RncYDnw7i7rjHP8DoZdBWYFUZCIvh4Y8owY5bMv0AouBF3rS/sDrd8/+VlFr9mBCY6tRzGN8LIXCF2dYZHv/wmIED51MPrueYA4ZZkDV2DNZ4Oe99LBDH7NNYoIQEeW/eKcyxgJkVom+UEvyrsWazrihRe9lYW/qpeFuDItuvDmu+ZugoK13j1EmVA6Lshl2YlpyZkPiSMOInPsbMrjwM=
  file: 
    - cours.pdf
    - cours.html
  skip_cleanup: true
  on:
    repo: mathintro/deuxieme_logiciel
