sudo: false
os: linux
language: haskell
addons:
  apt:
    packages:
    - texlive-latex-recommended lmodern texlive-fonts-recommended texlive-latex-extra
      texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-french
before_install:
- sudo add-apt-repository -y ppa:jonathonf/python-2.7
- sudo apt-get update
- sudo apt-get install python2.7  librsvg2-bin
install:
- wget https://github.com/jgm/pandoc/releases/download/2.0.6/pandoc-2.0.6-1-amd64.deb
- sudo dpkg -i pandoc-2.0.6-1-amd64.deb
- wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.0.1/linux-ghc80-pandoc20.tar.gz
- mkdir pandoc-crossref
- cd pandoc-crossref
- mv ../linux-ghc80-pandoc20.tar.gz .
- tar xzvf linux-ghc80-pandoc20.tar.gz
- cd ..
- export PATH=`pwd`/pandoc-crossref:$PATH
- sudo -H pip install --upgrade pip
- sudo -H pip install -U pandoc-numbering
cache:
- pip
script:
- make
after_deploy: |
  echo ${GH_TOKEN}
  git config --global user.email "travis@travis-ci.com"
  git config --global user.name "Travis CI"
  cd "$TRAVIS_BUILD_DIR"
  git clone https://${GITHUB_TOKEN}@github.com/mathintro/mathintro.github.io.git
  cd mathintro.github.io
  # This generates a `web` directory containing the website.
  cp ../cours.html deuxieme_logiciel/index.html
  git add deuxieme_logiciel/index.html
  git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  # Make sure to make the output quiet, or else the API token will leak!
  # This works because the API key can replace your password.
  git push --quiet https://${GITHUB_TOKEN}@github.com/mathintro/mathintro.github.io.git
env:
  global:
  - secure: NgJhUibG2X1K/3cqiYLALq+No0dFFGyWyAH3Q6j3Nd7ae39MI6nzs11fclf6jauKGOFciU8CMVD8I0whgngAFe+LDcoUoSLYxg9rRQHZjz4E8UyeRrJRtqPrAdOJY15MU5DZqMlKzICNkZ+Jb75ohSEBNJnw0h0QPDXWV4L6bNm7DWGuhX4RvbjDSAtd8e+tx/Sas4EECjDX3vGdRxZacHPE0d1Nw1FCYboRa0OG4N6IqiC09+/f0o7Bga/eTZI/9wp89/fcq9BqVeuyH/21idXJ4S2etuXIDB+Zi3gqpPVFBBQKG612JM8tozLjQlesvj7nGwEis5M7g3b2ps/IFBZYMfju8vSv7x7Lk94XyPkei/mSxZCHwo6PFRqXPla9MQ6RMDo5pp4nqSwW1DGoA6UkWVpAQPuuFHnyKE8r+L97gBt9pLOEDgEwg0N9f8w10aFdywdsRR9bSuzyf+QKDU48TOGRjlB9UVM8uK93cjdlisx1J5wp5ZbP/ZJo7DVnmAhIoux4iK5MondXaXOnITGGdp5KvA6TBsJ8FoBIWZ6l9nloKLpJMzxMJ81HCpeZv+jnPI+w+SxfvJP0aK5kSaMaJLgRv1klNwZ4VmpfImdenx/q72u5xfruhYqYIodSAsDi9/TY+50NhomJtgCfr2WI5d2G9yvwh6CCt5m1hAQ=
deploy:
  provider: releases
  api_key:
    secure: QOkajm1t++gYUKg8YJirmW/7C4UvU+xGcvieICfxSyTrMQQw+bopVbYFwTsP2qmJOUGdhdTmh8ngYWh7WFeTdwWqA2fZt4dr8jt7g/z+gI5ViTfkTCHmbNLvIUuG/vUK4Gy00iO/VGiZcEogZZqF2dQTu1j/WRk0czJRP5l9iys/4U6Q3RbS5HM6GwC8kZjpGWU2MnNByxXWS7ckGH/4z6XZZ0risSi+oGp9aRhO0iwEU+NKMjgkhnc/YLmAO28LrWOkGma42G8lYHu/oQqBUm8SdGIES0zxFM4TbIMPuFgCt+SLabv8Xn/Nri8WE7vc4b7Y5yLvZEVaf98qNicmJZcGq6/xCi4f6uFJzqCGWniDSskf5oBzJzWcd8KEWtDRAMdsKUZWwJS4Gg7ZBPUPXkYYly9UuFtYLsW35xpTmL1Sk2vS/2VCur7GYIRmofGzAcOooynIr++pg5y5W4jnVcx+FzhlLoqwm/RGANXFzblwkuz+ScoNPXK/HfXOAlNqLrIBGy5jcze7+HhidS5uqmo7mgbusegL69tkzNuWdj6BGGjdHC9L8nUilEccZKro3cMMkzpdUiij+iSnXrh8xJ8qWo+uLwtYzuXof2vxrPooNsEDogMu7cVhEsVI0WpA+SsTXINCBKumaB3HEnIaYfLYUMHCwSEJ8DLFRG9p1+A=
  file: cours.html cours.pdf
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
